version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trader
    container_name: trader
    restart: unless-stopped
    working_dir: /var/www/trader
    volumes:
      - .:/var/www/trader
      - .:/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      DB_HOST: db
      DB_DATABASE: trader
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: trader-nginx
    restart: unless-stopped
    ports:
      - "8050:85"
    volumes:
      - .:/var/www/trader
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: trader-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: